#!/usr/bin/env python

import os
import re
import sys

query_words = r'.+'.join(sys.argv[1:])

aws_app_root_dir = "~/.vim/aws.vim/"

security_groups = os\
                      .popen(
                          aws_app_root_dir + "list-security-groups"
                      )\
                      .read()\
                      .split('\n')

security_groups = [
                      x
                      for x
                      in security_groups 
                      if x != "" and not "NAME" in x
                  ]

target_groups = [x for x in security_groups if re.search(query_words, x)]

if len(target_groups) == 0:
    print("\ntarget groups matching the query '{}' is zero.".format(query_words))
    sys.exit()

print("\nYour security group details\n")
for target_group in target_groups: 
    sg_id = target_group.split("\t")[1]
    res = os.popen("aws ec2 describe-security-groups --group-ids {}".format(sg_id)).read()
    print(res)
