#!/usr/bin/env python

import os

label_security_groups = "SECURITYGROUPS"
label_name            = "Name\t"
label_tags            = "TAGS\t"

contraptions = os.popen(
                   "aws ec2 describe-instances | grep -e {} -e {}"
                       .format(
                           label_security_groups,
                           label_name
                       )
               ).read()

results            = []
contraptions_split = contraptions.split('\n')
i                  = 0

for line in contraptions_split:
    if line.startswith(label_tags):
       results.append(
           (
               line
                   .replace(label_security_groups, "")
                   .replace(label_tags, "")
                   .replace(label_name, "")
               + 
               contraptions_split[i - 1] 
                   .replace(label_security_groups, "")
           )
       )
    i = i + 1

print      
print       "NAME\tSECURITY GROUPS ID\tSECURITY GROUPS NAME"
for result in results:  
    print(result)
print      
